version: "3"

tasks:
  dev:
    cmds:
      - air
  docs:
    cmds:
      - swag init --dir ./cmd/http,./internal/todo
  build:
    cmds:
      - go build -o http-server cmd/http/main.go
  start:
    cmds:
      - ./http-server
