// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Thalles Passos"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/databases": {
            "post": {
                "description": "creates temporary dabase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Create temporary database",
                "parameters": [
                    {
                        "description": "Database details",
                        "name": "database",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/databases.createDatabaseInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/databases.createDatabaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "databases.createDatabaseInput": {
            "type": "object",
            "properties": {
                "database_type": {
                    "type": "string"
                },
                "expires_in_milliseconds": {
                    "type": "integer"
                }
            }
        },
        "databases.createDatabaseResponse": {
            "type": "object",
            "properties": {
                "connection_string": {
                    "type": "string"
                },
                "database_name": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TempDB Server API",
	Description:      "Create temporary databases for testing and development",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
