basePath: /
definitions:
  databases.createDatabaseInput:
    properties:
      database_type:
        type: string
      expires_in_milliseconds:
        type: integer
    type: object
  databases.createDatabaseResponse:
    properties:
      connection_string:
        type: string
      database_name:
        type: string
      expires_in:
        type: string
      host:
        type: string
      password:
        type: string
      user:
        type: string
    type: object
info:
  contact:
    name: Thalles Passos
  description: Create temporary databases for testing and development
  license:
    name: MIT
  title: TempDB Server API
  version: "2.0"
paths:
  /databases:
    post:
      consumes:
      - application/json
      description: creates temporary dabase
      parameters:
      - description: Database details
        in: body
        name: database
        required: true
        schema:
          $ref: '#/definitions/databases.createDatabaseInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/databases.createDatabaseResponse'
      summary: Create temporary database
      tags:
      - databases
swagger: "2.0"
